
development:
  stripe_secret_key: 'sk_test_51M7OsQJP4ezsauZibsxljWHkUdfYbxZhdkdxaKXqEURRCsa47V5W4xr62xNacXGdFa0RwWIgyq7WCDdg75TC2has00Hy16zh4q'
  stripe_publishable_key: 'pk_test_51M7OsQJP4ezsauZivsBGU7nLgAKbrKpKrrCvEaFg55PAoLMzbb8BC6PY1meEft09uRzy76dNBs4S1s0n9orRIQqq006aybne7l'
production:
  stripe_secret_key: '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'
  stripe_publishable_key: 'pk_live_51M7OsQJP4ezsauZi8ALhx4QR51badepB73btxCqCVSbm1Y8MRbqKWn3OaHNwvaEl5DOY6fxlmL11ve1gGNwpQpML00qplZoy8j'