development:
  stripe_secret_key: 'sk_test_51M2nVEAUWd5BoaTvArJWvqQ4qi3HQ1hNekOT9x3jI6Tc7RFCnpgaKlEDN1laIB6nToh9rZbHX3GUl6yB43APQ6Xd007vdPIAGj'
  stripe_publishable_key: 'pk_test_51M2nVEAUWd5BoaTvFBQHQCVMsc76HM3lDKmGcS0lnwbgATkEGOf81Z0UDjRm47DKkoO2hAWKs4cSWNh4tQBzTwXZ00xBSfY5mQ'

# production:
#   stripe_secret_key: 'sk_live_aLvPhyGtUwlLSHvms3KhCdrL'
#   stripe_publishable_key: 'pk_live_nbTqsm8Gg0eHGrQVRbWnjlyN'