stripe:
  development:
    stripe_secret_key: 'sk_test_51M7OsQJP4ezsauZibsxljWHkUdfYbxZhdkdxaKXqEURRCsa47V5W4xr62xNacXGdFa0RwWIgyq7WCDdg75TC2has00Hy16zh4q'
    stripe_publishable_key: 'pk_test_51M7OsQJP4ezsauZivsBGU7nLgAKbrKpKrrCvEaFg55PAoLMzbb8BC6PY1meEft09uRzy76dNBs4S1s0n9orRIQqq006aybne7l'
    webhook_signing_secret: 'whsec_c6f208a21dd071bb6473aec3643166c1c663bc3cb5d1e55c43ad9ea8507fcfec'
  production:
    stripe_secret_key: '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'
    stripe_publishable_key: 'pk_live_51M7OsQJP4ezsauZi8ALhx4QR51badepB73btxCqCVSbm1Y8MRbqKWn3OaHNwvaEl5DOY6fxlmL11ve1gGNwpQpML00qplZoy8j'
    webhook_signing_secret: 'whsec_c6f208a21dd071bb6473aec3643166c1c663bc3cb5d1e55c43ad9ea8507fcfec'
  pricing:
    monthly: 'price_1M9c5JJP4ezsauZiS4yWqGrK'
    annual: 'price_1M9c5JJP4ezsauZiS4yWqGrK'